#setwd("~/Documents/Daum 클라우드/R.WD/class2011")
#load("class_med.rda")
#ls()
#str(class_med)
#id.trt<-sample(class_med$id, size=33)
#id.trt
#class_med$group<-ifelse(class_med$id %in% id.trt, "treatment","control")
#tapply(class_med$naccesses, class_med$section, summary)
#tapply(class_med$naccesses, class_med$group, summary)
library("lattice")
library("latticeExtra")
quartz(width=7,height=7,dpi=72)
#layout(matrix(c(1,2,3),nrow=3))
bw1<-bwplot(~naccesses | factor(section), data=class_med, strip=strip.custom(strip.names=TRUE, var.name="Section"))
hist1<-histogram(~naccesses | factor(section), data=class_med, strip=strip.custom(strip.names=TRUE, var.name="Section"))
ecdf1<-ecdfplot(~naccesses | factor(section), data=class_med, strip=strip.custom(strip.names=TRUE, var.name="Section"))
print(bw1, position=c(0,2/3,1,1), more=TRUE)
print(hist1, position=c(0,1/3,1,2/3), more=TRUE)
print(ecdf1, position=c(0,0,1,1/3))
quartz(width=7,height=7,dpi=72)
#layout(matrix(c(1,2,3),nrow=3))
bw2<-bwplot(~naccesses | factor(group), data=class_med, strip=strip.custom(strip.names=TRUE, var.name="Group"))
hist2<-histogram(~naccesses | factor(group), data=class_med, strip=strip.custom(strip.names=TRUE, var.name="Group"))
ecdf2<-ecdfplot(~naccesses | factor(group), data=class_med, strip=strip.custom(strip.names=TRUE, var.name="Group"))
print(bw2, position=c(0,2/3,1,1), more=TRUE)
print(hist2, position=c(0,1/3,1,2/3), more=TRUE)
print(ecdf2, position=c(0,0,1,1/3))
