attach(USmelanoma)
jpeg("USmelanoma_latitude.jpg",width=640,height=640)
layout(matrix(c(1,2,3,4),2,2,byrow=TRUE))
plot(mortality~longitude)
plot(mortality~latitude)
plot(mortality~latitude,pch=as.integer(ocean))
legend("topright",c("Coast State","Land State"),pch=c(2,1),bty="n")
plot(mortality~latitude,pch=as.integer(ocean))
legend("topright",c("Coast State","Land State"),pch=c(2,1),bty="n")
text(latitude[latitude<32],mortality[latitude<32],rownames(USmelanoma)[latitude<32],pos=4)
detach(USmelanoma)
dev.off()